import Head from 'next/head'
import Image from 'next/image'
// import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
// import { Quicksand } from '@next/font/google'
import { Box, chakra, shouldForwardProp } from '@chakra-ui/react'
import Link from 'next/link'
import Header from '@/components/Header'
import {motion, isValidMotionProp} from 'framer-motion'
import Tombol from '@/components/Tombol'


// const inter = Inter({ subsets: ['latin'] })
// const quick = Quicksand({weight: '400' })
const ChakraBox = chakra(motion.div, {
  shouldForwardProp: (prop) => isValidMotionProp(prop) || shouldForwardProp(prop),
})
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Header /> */}
      <ChakraBox maxW='800px' m='100px auto 40px' textAlign='center'
      initial={{ opacity:0 }}
      animate={{ opacity:1 }}
      transition={{ delay:0.5, duration:1.5}}
      >
        <motion.h2 >
          Welcome to Pizza Joint
        </motion.h2>
        <Link href="/base">
          {/* <motion.button className={styles.btn}
           whileHover={{ 
            scale:1.1,
            textShadow:"0px 0px 8px rgb(255,255,255)",
            boxShadow:"0px 0px 8px rgb(255,255,255)"
          }}
          >
            Create Your Pizza
          </motion.button> */}
          <Tombol>Create Your Pizza</Tombol>
        </Link>
      </ChakraBox>
    </>
  )
}
